# Generated by Django 5.1.1 on 2024-09-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee_address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=100)),
            ],
        ),
    ]
